[package]
name = "bot"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
bus.workspace = true
chrono.workspace = true
clap.workspace = true
derive_more.workspace = true
figment.workspace = true
itertools.workspace = true
log.workspace = true
ordered-float.workspace = true
rayon.workspace = true
rustyline.workspace = true
sdk.workspace = true
serde.workspace = true
simple-logging.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
sdk = { workspace = true, features = ["test-utils"] }

[lints]
workspace = true
