/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountAchievementObjectiveSchema : Schema for a single objective within an account achievement, including progress.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAchievementObjectiveSchema {
    /// Type of objective.
    #[serde(rename = "type")]
    pub r#type: models::AchievementType,
    /// Target of the objective (e.g., item code, monster code).
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    /// Current progress for this objective.
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<i32>,
    /// Total required for this objective.
    #[serde(rename = "total")]
    pub total: i32,
}

impl AccountAchievementObjectiveSchema {
    /// Schema for a single objective within an account achievement, including progress.
    pub fn new(r#type: models::AchievementType, total: i32) -> AccountAchievementObjectiveSchema {
        AccountAchievementObjectiveSchema {
            r#type,
            target: None,
            progress: None,
            total,
        }
    }
}

