/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountStatus {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "founder")]
    Founder,
    #[serde(rename = "gold_founder")]
    GoldFounder,
    #[serde(rename = "vip_founder")]
    VipFounder,

}

impl std::fmt::Display for AccountStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Standard => write!(f, "standard"),
            Self::Founder => write!(f, "founder"),
            Self::GoldFounder => write!(f, "gold_founder"),
            Self::VipFounder => write!(f, "vip_founder"),
        }
    }
}

impl Default for AccountStatus {
    fn default() -> AccountStatus {
        Self::Standard
    }
}

