/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeEmailSchema {
    /// Your current email.
    #[serde(rename = "current_email")]
    pub current_email: String,
    /// New email.
    #[serde(rename = "new_email")]
    pub new_email: String,
}

impl ChangeEmailSchema {
    pub fn new(current_email: String, new_email: String) -> ChangeEmailSchema {
        ChangeEmailSchema {
            current_email,
            new_email,
        }
    }
}

