/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CharacterMovementDataSchema {
    /// Cooldown details
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// Destination details.
    #[serde(rename = "destination")]
    pub destination: models::MapSchema,
    /// Path taken from start to destination (list of coordinates)
    #[serde(rename = "path")]
    pub path: Vec<Vec<i32>>,
    /// Character details.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl CharacterMovementDataSchema {
    pub fn new(cooldown: models::CooldownSchema, destination: models::MapSchema, path: Vec<Vec<i32>>, character: models::CharacterSchema) -> CharacterMovementDataSchema {
        CharacterMovementDataSchema {
            cooldown,
            destination,
            path,
            character,
        }
    }
}

