/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CharacterStatsSchema {
    #[serde(rename = "monsters_killed", skip_serializing_if = "Option::is_none")]
    pub monsters_killed: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "resources_gathered", skip_serializing_if = "Option::is_none")]
    pub resources_gathered: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "items_crafted", skip_serializing_if = "Option::is_none")]
    pub items_crafted: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "action_counts", skip_serializing_if = "Option::is_none")]
    pub action_counts: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "deaths", skip_serializing_if = "Option::is_none")]
    pub deaths: Option<i32>,
}

impl CharacterStatsSchema {
    pub fn new() -> CharacterStatsSchema {
        CharacterStatsSchema {
            monsters_killed: None,
            resources_gathered: None,
            items_crafted: None,
            action_counts: None,
            deaths: None,
        }
    }
}

