/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CharacterTransitionDataSchema {
    /// Cooldown details
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// Destination map details.
    #[serde(rename = "destination")]
    pub destination: models::MapSchema,
    /// Transition details.
    #[serde(rename = "transition")]
    pub transition: models::TransitionSchema,
    /// Character details.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl CharacterTransitionDataSchema {
    pub fn new(cooldown: models::CooldownSchema, destination: models::MapSchema, transition: models::TransitionSchema, character: models::CharacterSchema) -> CharacterTransitionDataSchema {
        CharacterTransitionDataSchema {
            cooldown,
            destination,
            transition,
            character,
        }
    }
}

