/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CharacterFightDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: Box<models::CooldownSchema>,
    /// Character fight details.
    #[serde(rename = "fight")]
    pub fight: Box<models::CharacterFightSchema>,
    /// All characters involved.
    #[serde(rename = "characters")]
    pub characters: Vec<models::CharacterSchema>,
}

impl CharacterFightDataSchema {
    pub fn new(cooldown: models::CooldownSchema, fight: models::CharacterFightSchema, characters: Vec<models::CharacterSchema>) -> CharacterFightDataSchema {
        CharacterFightDataSchema {
            cooldown: Box::new(cooldown),
            fight: Box::new(fight),
            characters,
        }
    }
}

