/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckoutResponseSchema : Checkout session response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutResponseSchema {
    /// Stripe checkout URL for payment.
    #[serde(rename = "checkout_url")]
    pub checkout_url: String,
    /// Stripe checkout session ID.
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl CheckoutResponseSchema {
    /// Checkout session response.
    pub fn new(checkout_url: String, session_id: String) -> CheckoutResponseSchema {
        CheckoutResponseSchema {
            checkout_url,
            session_id,
        }
    }
}

