/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClaimPendingItemDataSchema : Data schema for claim pending item action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimPendingItemDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// The claimed pending item.
    #[serde(rename = "item")]
    pub item: models::PendingItemSchema,
    /// Character details.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl ClaimPendingItemDataSchema {
    /// Data schema for claim pending item action.
    pub fn new(cooldown: models::CooldownSchema, item: models::PendingItemSchema, character: models::CharacterSchema) -> ClaimPendingItemDataSchema {
        ClaimPendingItemDataSchema {
            cooldown,
            item,
            character,
        }
    }
}

