/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClaimPendingItemDataSchema : Data schema for claim pending item action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimPendingItemDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: Box<models::CooldownSchema>,
    /// The claimed pending item.
    #[serde(rename = "item")]
    pub item: Box<models::PendingItemSchema>,
    /// Character details.
    #[serde(rename = "character")]
    pub character: Box<models::CharacterSchema>,
}

impl ClaimPendingItemDataSchema {
    /// Data schema for claim pending item action.
    pub fn new(cooldown: models::CooldownSchema, item: models::PendingItemSchema, character: models::CharacterSchema) -> ClaimPendingItemDataSchema {
        ClaimPendingItemDataSchema {
            cooldown: Box::new(cooldown),
            item: Box::new(item),
            character: Box::new(character),
        }
    }
}

