/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClaimPendingItemResponseSchema : Response schema for claim pending item action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimPendingItemResponseSchema {
    /// Response data containing cooldown, item, and character.
    #[serde(rename = "data")]
    pub data: Box<models::ClaimPendingItemDataSchema>,
}

impl ClaimPendingItemResponseSchema {
    /// Response schema for claim pending item action.
    pub fn new(data: models::ClaimPendingItemDataSchema) -> ClaimPendingItemResponseSchema {
        ClaimPendingItemResponseSchema {
            data: Box::new(data),
        }
    }
}

