/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteItemSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// Item details.
    #[serde(rename = "item")]
    pub item: models::SimpleItemSchema,
    /// Player details.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl DeleteItemSchema {
    pub fn new(cooldown: models::CooldownSchema, item: models::SimpleItemSchema, character: models::CharacterSchema) -> DeleteItemSchema {
        DeleteItemSchema {
            cooldown,
            item,
            character,
        }
    }
}

