/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DestinationSchema {
    /// The x coordinate of the destination.
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<i32>,
    /// The y coordinate of the destination.
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<i32>,
    /// The map ID of the destination.
    #[serde(rename = "map_id", skip_serializing_if = "Option::is_none")]
    pub map_id: Option<i32>,
}

impl DestinationSchema {
    pub fn new() -> DestinationSchema {
        DestinationSchema {
            x: None,
            y: None,
            map_id: None,
        }
    }
}

