/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EffectType {
    #[serde(rename = "equipment")]
    Equipment,
    #[serde(rename = "consumable")]
    Consumable,
    #[serde(rename = "combat")]
    Combat,

}

impl std::fmt::Display for EffectType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Equipment => write!(f, "equipment"),
            Self::Consumable => write!(f, "consumable"),
            Self::Combat => write!(f, "combat"),
        }
    }
}

impl Default for EffectType {
    fn default() -> EffectType {
        Self::Equipment
    }
}

