/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorSchema {
    /// Error code
    #[serde(rename = "code")]
    pub code: i32,
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
    /// Additional error data (used primarily for validation errors)
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ErrorSchema {
    pub fn new(code: i32, message: String) -> ErrorSchema {
        ErrorSchema {
            code,
            message,
            data: None,
        }
    }
}

