/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSchema {
    /// Name of the event.
    #[serde(rename = "name")]
    pub name: String,
    /// Code of the event.
    #[serde(rename = "code")]
    pub code: String,
    /// Content of the event.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<models::EventContentSchema>>,
    /// Map list of the event.
    #[serde(rename = "maps")]
    pub maps: Vec<models::EventMapSchema>,
    /// Duration in minutes.
    #[serde(rename = "duration")]
    pub duration: i32,
    /// Rate spawn of the event. (1/rate every minute)
    #[serde(rename = "rate")]
    pub rate: i32,
    /// Cooldown in minutes before the event can be spawned with gems.
    #[serde(rename = "cooldown", skip_serializing_if = "Option::is_none")]
    pub cooldown: Option<i32>,
    /// Gems spawn cooldown expiration datetime (null if not on cooldown).
    #[serde(rename = "cooldown_expiration", skip_serializing_if = "Option::is_none")]
    pub cooldown_expiration: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Price in gems to spawn the event. Null if not purchasable.
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    /// Transition to add to the map when event is active.
    #[serde(rename = "transition", skip_serializing_if = "Option::is_none")]
    pub transition: Option<Box<models::TransitionSchema>>,
}

impl EventSchema {
    pub fn new(name: String, code: String, maps: Vec<models::EventMapSchema>, duration: i32, rate: i32) -> EventSchema {
        EventSchema {
            name,
            code,
            content: None,
            maps,
            duration,
            rate,
            cooldown: None,
            cooldown_expiration: None,
            price: None,
            transition: None,
        }
    }
}

