/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeBuyOrderCreationSchema : Schema for creating a buy order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeBuyOrderCreationSchema {
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Item quantity.
    #[serde(rename = "quantity")]
    pub quantity: u32,
    /// Item price per unit.
    #[serde(rename = "price")]
    pub price: u32,
}

impl GeBuyOrderCreationSchema {
    /// Schema for creating a buy order.
    pub fn new(code: String, quantity: u32, price: u32) -> GeBuyOrderCreationSchema {
        GeBuyOrderCreationSchema {
            code,
            quantity,
            price,
        }
    }
}

