/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeFillBuyOrderSchema : Schema for filling a buy order (selling items to a buy order).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeFillBuyOrderSchema {
    /// Buy order id.
    #[serde(rename = "id")]
    pub id: String,
    /// Item quantity to sell.
    #[serde(rename = "quantity")]
    pub quantity: u32,
}

impl GeFillBuyOrderSchema {
    /// Schema for filling a buy order (selling items to a buy order).
    pub fn new(id: String, quantity: u32) -> GeFillBuyOrderSchema {
        GeFillBuyOrderSchema {
            id,
            quantity,
        }
    }
}

