/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeOrderSchema {
    /// Order id.
    #[serde(rename = "id")]
    pub id: String,
    /// Order type (sell or buy).
    #[serde(rename = "type")]
    pub r#type: models::GeOrderType,
    /// Account linked to the order.
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Item quantity.
    #[serde(rename = "quantity")]
    pub quantity: u32,
    /// Item price per unit.
    #[serde(rename = "price")]
    pub price: u32,
    /// Order created at.
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl GeOrderSchema {
    pub fn new(id: String, r#type: models::GeOrderType, code: String, quantity: u32, price: u32, created_at: chrono::DateTime<chrono::FixedOffset>) -> GeOrderSchema {
        GeOrderSchema {
            id,
            r#type,
            account: None,
            code,
            quantity,
            price,
            created_at,
        }
    }
}

