/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeOrderType : Type of Grand Exchange order.
/// Type of Grand Exchange order.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GeOrderType {
    #[serde(rename = "sell")]
    Sell,
    #[serde(rename = "buy")]
    Buy,

}

impl std::fmt::Display for GeOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sell => write!(f, "sell"),
            Self::Buy => write!(f, "buy"),
        }
    }
}

impl Default for GeOrderType {
    fn default() -> GeOrderType {
        Self::Sell
    }
}

