/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeOrderTransactionSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// Order details.
    #[serde(rename = "order")]
    pub order: models::GeOrderCreatedSchema,
    /// Character details.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl GeOrderTransactionSchema {
    pub fn new(cooldown: models::CooldownSchema, order: models::GeOrderCreatedSchema, character: models::CharacterSchema) -> GeOrderTransactionSchema {
        GeOrderTransactionSchema {
            cooldown,
            order,
            character,
        }
    }
}

