/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GemShopSkinCatalogItemSchema {
    /// Skin code.
    #[serde(rename = "code")]
    pub code: String,
    /// Skin name.
    #[serde(rename = "name")]
    pub name: String,
    /// Skin description.
    #[serde(rename = "description")]
    pub description: String,
    /// Skin price in gems.
    #[serde(rename = "price")]
    pub price: i32,
}

impl GemShopSkinCatalogItemSchema {
    pub fn new(code: String, name: String, description: String, price: i32) -> GemShopSkinCatalogItemSchema {
        GemShopSkinCatalogItemSchema {
            code,
            name,
            description,
            price,
        }
    }
}

