/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GemShopSubscriptionCatalogItemSchema {
    /// Subscription offer code.
    #[serde(rename = "code")]
    pub code: String,
    /// Subscription offer name.
    #[serde(rename = "name")]
    pub name: String,
    /// Subscription duration in days.
    #[serde(rename = "duration_days")]
    pub duration_days: i32,
    /// Subscription price in gems.
    #[serde(rename = "price")]
    pub price: i32,
}

impl GemShopSubscriptionCatalogItemSchema {
    pub fn new(code: String, name: String, duration_days: i32, price: i32) -> GemShopSubscriptionCatalogItemSchema {
        GemShopSubscriptionCatalogItemSchema {
            code,
            name,
            duration_days,
            price,
        }
    }
}

