/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiveItemsSchema {
    /// List of items to give
    #[serde(rename = "items")]
    pub items: Vec<models::SimpleItemSchema>,
    /// Character name. The name of the character who will receive the items.
    #[serde(rename = "character")]
    pub character: String,
}

impl GiveItemsSchema {
    pub fn new(items: Vec<models::SimpleItemSchema>, character: String) -> GiveItemsSchema {
        GiveItemsSchema {
            items,
            character,
        }
    }
}

