/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiveItemDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: models::CooldownSchema,
    /// Items given.
    #[serde(rename = "items")]
    pub items: Vec<models::SimpleItemSchema>,
    /// Character details of the receiving character.
    #[serde(rename = "receiver_character")]
    pub receiver_character: models::CharacterSchema,
    /// Character details of the sending character.
    #[serde(rename = "character")]
    pub character: models::CharacterSchema,
}

impl GiveItemDataSchema {
    pub fn new(cooldown: models::CooldownSchema, items: Vec<models::SimpleItemSchema>, receiver_character: models::CharacterSchema, character: models::CharacterSchema) -> GiveItemDataSchema {
        GiveItemDataSchema {
            cooldown,
            items,
            receiver_character,
            character,
        }
    }
}

