/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NpcType {
    #[serde(rename = "merchant")]
    Merchant,
    #[serde(rename = "trader")]
    Trader,

}

impl std::fmt::Display for NpcType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Merchant => write!(f, "merchant"),
            Self::Trader => write!(f, "trader"),
        }
    }
}

impl Default for NpcType {
    fn default() -> NpcType {
        Self::Merchant
    }
}

