/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NpcSchema {
    /// Name of the NPC.
    #[serde(rename = "name")]
    pub name: String,
    /// The code of the NPC. This is the NPC's unique identifier (ID).
    #[serde(rename = "code")]
    pub code: String,
    /// Description of the NPC.
    #[serde(rename = "description")]
    pub description: String,
    /// Type of the NPC.
    #[serde(rename = "type")]
    pub r#type: models::NpcType,
}

impl NpcSchema {
    pub fn new(name: String, code: String, description: String, r#type: models::NpcType) -> NpcSchema {
        NpcSchema {
            name,
            code,
            description,
            r#type,
        }
    }
}

