/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PendingItemSource : Source types for pending items.
/// Source types for pending items.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PendingItemSource {
    #[serde(rename = "achievement")]
    Achievement,
    #[serde(rename = "grand_exchange")]
    GrandExchange,
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "event")]
    Event,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for PendingItemSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Achievement => write!(f, "achievement"),
            Self::GrandExchange => write!(f, "grand_exchange"),
            Self::Admin => write!(f, "admin"),
            Self::Event => write!(f, "event"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for PendingItemSource {
    fn default() -> PendingItemSource {
        Self::Achievement
    }
}

