/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseHistorySchema {
    /// Type of purchase.
    #[serde(rename = "type")]
    pub r#type: models::PurchaseType,
    /// Description of the purchase.
    #[serde(rename = "description")]
    pub description: String,
    /// Amount in cents.
    #[serde(rename = "amount")]
    pub amount: i32,
    /// Gems credited from this purchase.
    #[serde(rename = "gems_credited", skip_serializing_if = "Option::is_none")]
    pub gems_credited: Option<i32>,
    /// When the purchase was made.
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PurchaseHistorySchema {
    pub fn new(r#type: models::PurchaseType, description: String, amount: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> PurchaseHistorySchema {
        PurchaseHistorySchema {
            r#type,
            description,
            amount,
            gems_credited: None,
            created_at,
        }
    }
}

