/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RaidScheduleSchema {
    /// UTC weekdays when the raid opens.
    #[serde(rename = "weekdays")]
    pub weekdays: Vec<models::RaidWeekday>,
    /// UTC hour when the raid opens.
    #[serde(rename = "start_hour_utc", skip_serializing_if = "Option::is_none")]
    pub start_hour_utc: Option<u32>,
    /// UTC minute when the raid opens.
    #[serde(rename = "start_minute_utc", skip_serializing_if = "Option::is_none")]
    pub start_minute_utc: Option<u32>,
    /// Maximum raid duration in hours.
    #[serde(rename = "duration_hours", skip_serializing_if = "Option::is_none")]
    pub duration_hours: Option<u32>,
}

impl RaidScheduleSchema {
    pub fn new(weekdays: Vec<models::RaidWeekday>) -> RaidScheduleSchema {
        RaidScheduleSchema {
            weekdays,
            start_hour_utc: None,
            start_minute_utc: None,
            duration_hours: None,
        }
    }
}

