/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RaidRewardsSchema {
    /// Items granted based on cumulative damage dealt.
    #[serde(rename = "damage_rewards", skip_serializing_if = "Option::is_none")]
    pub damage_rewards: Option<Vec<models::RaidDamageRewardSchema>>,
    /// Items granted based on leaderboard rank.
    #[serde(rename = "leaderboard", skip_serializing_if = "Option::is_none")]
    pub leaderboard: Option<Vec<models::RaidRankRewardSchema>>,
}

impl RaidRewardsSchema {
    pub fn new() -> RaidRewardsSchema {
        RaidRewardsSchema {
            damage_rewards: None,
            leaderboard: None,
        }
    }
}

