/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitScopeSchema {
    #[serde(rename = "second", skip_serializing_if = "Option::is_none")]
    pub second: Option<Box<models::RateLimitWindowSchema>>,
    #[serde(rename = "minute", skip_serializing_if = "Option::is_none")]
    pub minute: Option<Box<models::RateLimitWindowSchema>>,
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<Box<models::RateLimitWindowSchema>>,
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<Box<models::RateLimitWindowSchema>>,
}

impl RateLimitScopeSchema {
    pub fn new() -> RateLimitScopeSchema {
        RateLimitScopeSchema {
            second: None,
            minute: None,
            hour: None,
            day: None,
        }
    }
}

