/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecyclingSchema {
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Quantity of items to recycle.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<u32>,
    /// Whether to use enhanced recycling.
    #[serde(rename = "enhanced", skip_serializing_if = "Option::is_none")]
    pub enhanced: Option<bool>,
}

impl RecyclingSchema {
    pub fn new(code: String) -> RecyclingSchema {
        RecyclingSchema {
            code,
            quantity: None,
            enhanced: None,
        }
    }
}

