/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameCharacterDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: Box<models::CooldownSchema>,
    /// Previous character name.
    #[serde(rename = "old_name")]
    pub old_name: String,
    /// New character name.
    #[serde(rename = "new_name")]
    pub new_name: String,
    /// Player details.
    #[serde(rename = "character")]
    pub character: Box<models::CharacterSchema>,
}

impl RenameCharacterDataSchema {
    pub fn new(cooldown: models::CooldownSchema, old_name: String, new_name: String, character: models::CharacterSchema) -> RenameCharacterDataSchema {
        RenameCharacterDataSchema {
            cooldown: Box::new(cooldown),
            old_name,
            new_name,
            character: Box::new(character),
        }
    }
}

