/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeasonSchema {
    /// Season name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Season number.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    /// Season start date.
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Season rewards with required achievement points, sorted by points ascending.
    #[serde(rename = "rewards")]
    pub rewards: Vec<models::StatusSeasonRewardSchema>,
}

impl SeasonSchema {
    pub fn new(rewards: Vec<models::StatusSeasonRewardSchema>) -> SeasonSchema {
        SeasonSchema {
            name: None,
            number: None,
            start_date: None,
            rewards,
        }
    }
}

