/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpawnEventRequest : Model for the request to spawn a specific event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpawnEventRequest {
    /// Code of the event to spawn
    #[serde(rename = "code")]
    pub code: String,
}

impl SpawnEventRequest {
    /// Model for the request to spawn a specific event
    pub fn new(code: String) -> SpawnEventRequest {
        SpawnEventRequest {
            code,
        }
    }
}

