/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaticDataPageTaskFullSchema {
    #[serde(rename = "data")]
    pub data: Vec<models::TaskFullSchema>,
    #[serde(rename = "total")]
    pub total: u32,
    #[serde(rename = "page")]
    pub page: u32,
    #[serde(rename = "size")]
    pub size: u32,
    #[serde(rename = "pages")]
    pub pages: u32,
}

impl StaticDataPageTaskFullSchema {
    pub fn new(data: Vec<models::TaskFullSchema>, total: u32, page: u32, size: u32, pages: u32) -> StaticDataPageTaskFullSchema {
        StaticDataPageTaskFullSchema {
            data,
            total,
            page,
            size,
            pages,
        }
    }
}

