/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageEffectSchema {
    /// Effect code.
    #[serde(rename = "code")]
    pub code: String,
    /// Effect value.
    #[serde(rename = "value")]
    pub value: i32,
}

impl StorageEffectSchema {
    pub fn new(code: String, value: i32) -> StorageEffectSchema {
        StorageEffectSchema {
            code,
            value,
        }
    }
}

