/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StripeSubscriptionPlan : Stripe subscription plan type.
/// Stripe subscription plan type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StripeSubscriptionPlan {
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "annual")]
    Annual,

}

impl std::fmt::Display for StripeSubscriptionPlan {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Monthly => write!(f, "monthly"),
            Self::Annual => write!(f, "annual"),
        }
    }
}

impl Default for StripeSubscriptionPlan {
    fn default() -> StripeSubscriptionPlan {
        Self::Monthly
    }
}

