/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribeRequestSchema {
    /// Stripe membership plan to purchase.
    #[serde(rename = "plan")]
    pub plan: models::StripeSubscriptionPlan,
    /// Whether to create a recurring Stripe subscription. Set to false to buy membership time once.
    #[serde(rename = "recurring", skip_serializing_if = "Option::is_none")]
    pub recurring: Option<bool>,
}

impl SubscribeRequestSchema {
    pub fn new(plan: models::StripeSubscriptionPlan) -> SubscribeRequestSchema {
        SubscribeRequestSchema {
            plan,
            recurring: None,
        }
    }
}

