/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionSchema {
    /// Subscription plan (monthly, annual, or prepaid).
    #[serde(rename = "plan")]
    pub plan: models::SubscriptionPlan,
    /// How the subscription was purchased. Mixed means both gems and member tokens were used.
    #[serde(rename = "purchase_source")]
    pub purchase_source: PurchaseSource,
    /// Subscription status (active, cancelled, past_due, expired).
    #[serde(rename = "status")]
    pub status: String,
    /// Start of the current billing period.
    #[serde(rename = "current_period_start")]
    pub current_period_start: chrono::DateTime<chrono::FixedOffset>,
    /// End of the current billing period.
    #[serde(rename = "current_period_end")]
    pub current_period_end: chrono::DateTime<chrono::FixedOffset>,
    /// When the subscription was created.
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// When the subscription was cancelled.
    #[serde(rename = "cancelled_at", skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl SubscriptionSchema {
    pub fn new(plan: models::SubscriptionPlan, purchase_source: PurchaseSource, status: String, current_period_start: chrono::DateTime<chrono::FixedOffset>, current_period_end: chrono::DateTime<chrono::FixedOffset>, created_at: chrono::DateTime<chrono::FixedOffset>) -> SubscriptionSchema {
        SubscriptionSchema {
            plan,
            purchase_source,
            status,
            current_period_start,
            current_period_end,
            created_at,
            cancelled_at: None,
        }
    }
}
/// How the subscription was purchased. Mixed means both gems and member tokens were used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PurchaseSource {
    #[serde(rename = "stripe")]
    Stripe,
    #[serde(rename = "gems")]
    Gems,
    #[serde(rename = "member_token")]
    MemberToken,
    #[serde(rename = "mixed")]
    Mixed,
}

impl Default for PurchaseSource {
    fn default() -> PurchaseSource {
        Self::Stripe
    }
}

