/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransitionSchema {
    /// ID of the destination map.
    #[serde(rename = "map_id")]
    pub map_id: i32,
    /// Position X of the destination.
    #[serde(rename = "x")]
    pub x: i32,
    /// Position Y of the destination.
    #[serde(rename = "y")]
    pub y: i32,
    /// Layer of the destination.
    #[serde(rename = "layer")]
    pub layer: models::MapLayer,
    /// Conditions for the transition.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::ConditionSchema>>,
}

impl TransitionSchema {
    pub fn new(map_id: i32, x: i32, y: i32, layer: models::MapLayer) -> TransitionSchema {
        TransitionSchema {
            map_id,
            x,
            y,
            layer,
            conditions: None,
        }
    }
}

