/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`buy_custom_design_gems_shop_buy_custom_design_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BuyCustomDesignGemsShopBuyCustomDesignPostError {
    Status563(models::ErrorResponseSchema),
    Status404(models::ErrorResponseSchema),
    Status422(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`buy_skin_gems_shop_skin_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BuySkinGemsShopSkinPostError {
    Status404(models::ErrorResponseSchema),
    Status551(models::ErrorResponseSchema),
    Status552(models::ErrorResponseSchema),
    Status563(models::ErrorResponseSchema),
    Status422(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`buy_spawn_event_gems_shop_spawn_event_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BuySpawnEventGemsShopSpawnEventPostError {
    Status563(models::ErrorResponseSchema),
    Status404(models::ErrorResponseSchema),
    Status564(models::ErrorResponseSchema),
    Status566(models::ErrorResponseSchema),
    Status571(models::ErrorResponseSchema),
    Status422(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`buy_subscription_gems_shop_subscription_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BuySubscriptionGemsShopSubscriptionPostError {
    Status563(models::ErrorResponseSchema),
    Status573(models::ErrorResponseSchema),
    Status422(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_catalog_gems_shop_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCatalogGemsShopGetError {
    UnknownValue(serde_json::Value),
}


/// Buy a custom design using gems.
pub async fn buy_custom_design_gems_shop_buy_custom_design_post(configuration: &configuration::Configuration, buy_custom_design_request_schema: models::BuyCustomDesignRequestSchema) -> Result<models::GemShopCustomDesignPurchaseResponseSchema, Error<BuyCustomDesignGemsShopBuyCustomDesignPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_buy_custom_design_request_schema = buy_custom_design_request_schema;

    let uri_str = format!("{}/gems_shop/buy_custom_design", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_buy_custom_design_request_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GemShopCustomDesignPurchaseResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GemShopCustomDesignPurchaseResponseSchema`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BuyCustomDesignGemsShopBuyCustomDesignPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Buy a skin from the gems shop using gems.
pub async fn buy_skin_gems_shop_skin_post(configuration: &configuration::Configuration, buy_skin_request_schema: models::BuySkinRequestSchema) -> Result<models::BuySkinResponseSchema, Error<BuySkinGemsShopSkinPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_buy_skin_request_schema = buy_skin_request_schema;

    let uri_str = format!("{}/gems_shop/skin", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_buy_skin_request_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BuySkinResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BuySkinResponseSchema`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BuySkinGemsShopSkinPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Spawn an event from the gems shop using gems.
pub async fn buy_spawn_event_gems_shop_spawn_event_post(configuration: &configuration::Configuration, spawn_event_request_schema: models::SpawnEventRequestSchema) -> Result<models::ActiveEventResponseSchema, Error<BuySpawnEventGemsShopSpawnEventPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_spawn_event_request_schema = spawn_event_request_schema;

    let uri_str = format!("{}/gems_shop/spawn_event", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_spawn_event_request_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ActiveEventResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ActiveEventResponseSchema`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BuySpawnEventGemsShopSpawnEventPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Buy or extend membership by 30 days using gems. Unavailable while a Stripe subscription is active.
pub async fn buy_subscription_gems_shop_subscription_post(configuration: &configuration::Configuration, ) -> Result<models::GemShopSubscriptionResponseSchema, Error<BuySubscriptionGemsShopSubscriptionPostError>> {

    let uri_str = format!("{}/gems_shop/subscription", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GemShopSubscriptionResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GemShopSubscriptionResponseSchema`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BuySubscriptionGemsShopSubscriptionPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return the gems shop catalog.
pub async fn get_catalog_gems_shop_get(configuration: &configuration::Configuration, ) -> Result<models::GemShopCatalogResponseSchema, Error<GetCatalogGemsShopGetError>> {

    let uri_str = format!("{}/gems_shop/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GemShopCatalogResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GemShopCatalogResponseSchema`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCatalogGemsShopGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

