/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_accounts_leaderboard_leaderboard_accounts_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAccountsLeaderboardLeaderboardAccountsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_characters_leaderboard_leaderboard_characters_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCharactersLeaderboardLeaderboardCharactersGetError {
    UnknownValue(serde_json::Value),
}


/// Fetch leaderboard details.
pub fn get_accounts_leaderboard_leaderboard_accounts_get(configuration: &configuration::Configuration, sort: Option<models::AccountLeaderboardType>, name: Option<&str>, page: Option<u32>, size: Option<u32>) -> Result<models::DataPageAccountLeaderboardSchema, Error<GetAccountsLeaderboardLeaderboardAccountsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_sort = sort;
    let p_query_name = name;
    let p_query_page = page;
    let p_query_size = size;

    let uri_str = format!("{}/leaderboard/accounts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageAccountLeaderboardSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DataPageAccountLeaderboardSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetAccountsLeaderboardLeaderboardAccountsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch leaderboard details.
pub fn get_characters_leaderboard_leaderboard_characters_get(configuration: &configuration::Configuration, sort: Option<models::CharacterLeaderboardType>, name: Option<&str>, page: Option<u32>, size: Option<u32>) -> Result<models::DataPageCharacterLeaderboardSchema, Error<GetCharactersLeaderboardLeaderboardCharactersGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_sort = sort;
    let p_query_name = name;
    let p_query_page = page;
    let p_query_size = size;

    let uri_str = format!("{}/leaderboard/characters", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageCharacterLeaderboardSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DataPageCharacterLeaderboardSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetCharactersLeaderboardLeaderboardCharactersGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

