/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_all_maps_maps_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllMapsMapsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_layer_maps_maps_layer_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLayerMapsMapsLayerGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_map_by_id_maps_id_map_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMapByIdMapsIdMapIdGetError {
    Status404(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_map_by_position_maps_layer_xy_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMapByPositionMapsLayerXyGetError {
    Status404(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}


/// Fetch maps details.
pub fn get_all_maps_maps_get(configuration: &configuration::Configuration, layer: Option<models::MapLayer>, content_type: Option<models::MapContentType>, content_code: Option<&str>, hide_blocked_maps: Option<bool>, page: Option<u32>, size: Option<u32>) -> Result<models::DataPageMapSchema, Error<GetAllMapsMapsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_layer = layer;
    let p_query_content_type = content_type;
    let p_query_content_code = content_code;
    let p_query_hide_blocked_maps = hide_blocked_maps;
    let p_query_page = page;
    let p_query_size = size;

    let uri_str = format!("{}/maps", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_layer {
        req_builder = req_builder.query(&[("layer", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_content_type {
        req_builder = req_builder.query(&[("content_type", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_content_code {
        req_builder = req_builder.query(&[("content_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_hide_blocked_maps {
        req_builder = req_builder.query(&[("hide_blocked_maps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageMapSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DataPageMapSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetAllMapsMapsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch maps details.
pub fn get_layer_maps_maps_layer_get(configuration: &configuration::Configuration, layer: &str, content_type: Option<&str>, content_code: Option<&str>, hide_blocked_maps: Option<bool>, page: Option<u32>, size: Option<u32>) -> Result<models::DataPageMapSchema, Error<GetLayerMapsMapsLayerGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_layer = layer;
    let p_query_content_type = content_type;
    let p_query_content_code = content_code;
    let p_query_hide_blocked_maps = hide_blocked_maps;
    let p_query_page = page;
    let p_query_size = size;

    let uri_str = format!("{}/maps/{layer}", configuration.base_path, layer=p_path_layer.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_content_type {
        req_builder = req_builder.query(&[("content_type", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_content_code {
        req_builder = req_builder.query(&[("content_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_hide_blocked_maps {
        req_builder = req_builder.query(&[("hide_blocked_maps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageMapSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DataPageMapSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetLayerMapsMapsLayerGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve the details of a map by its unique ID.
pub fn get_map_by_id_maps_id_map_id_get(configuration: &configuration::Configuration, map_id: i32) -> Result<models::MapResponseSchema, Error<GetMapByIdMapsIdMapIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_map_id = map_id;

    let uri_str = format!("{}/maps/id/{map_id}", configuration.base_path, map_id=p_path_map_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MapResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MapResponseSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetMapByIdMapsIdMapIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve the details of a map by layer and coordinates.
pub fn get_map_by_position_maps_layer_xy_get(configuration: &configuration::Configuration, layer: &str, x: i32, y: i32) -> Result<models::MapResponseSchema, Error<GetMapByPositionMapsLayerXyGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_layer = layer;
    let p_path_x = x;
    let p_path_y = y;

    let uri_str = format!("{}/maps/{layer}/{x}/{y}", configuration.base_path, layer=p_path_layer.to_string(), x=p_path_x, y=p_path_y);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MapResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MapResponseSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetMapByPositionMapsLayerXyGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

