/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_all_resources_resources_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllResourcesResourcesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_resource_resources_code_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetResourceResourcesCodeGetError {
    Status404(models::ErrorResponseSchema),
    UnknownValue(serde_json::Value),
}


/// Fetch resources details.
pub fn get_all_resources_resources_get(configuration: &configuration::Configuration, min_level: Option<u32>, max_level: Option<u32>, skill: Option<models::GatheringSkill>, drop: Option<&str>, page: Option<u32>, size: Option<u32>) -> Result<models::DataPageResourceSchema, Error<GetAllResourcesResourcesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_min_level = min_level;
    let p_query_max_level = max_level;
    let p_query_skill = skill;
    let p_query_drop = drop;
    let p_query_page = page;
    let p_query_size = size;

    let uri_str = format!("{}/resources", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_min_level {
        req_builder = req_builder.query(&[("min_level", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_level {
        req_builder = req_builder.query(&[("max_level", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_skill {
        req_builder = req_builder.query(&[("skill", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_drop {
        req_builder = req_builder.query(&[("drop", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageResourceSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DataPageResourceSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetAllResourcesResourcesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve the details of a resource.
pub fn get_resource_resources_code_get(configuration: &configuration::Configuration, code: &str) -> Result<models::ResourceResponseSchema, Error<GetResourceResourcesCodeGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_code = code;

    let uri_str = format!("{}/resources/{code}", configuration.base_path, code=crate::apis::urlencode(p_path_code));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ResourceResponseSchema`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ResourceResponseSchema`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<GetResourceResourcesCodeGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

